### ISSUE TITLE
what font

### ISSUE THREAD

**Issue by allyraza** [knewter/dotfiles#1]
Hi Josh,

what font are you using?

**Comment by knewter** [comment]
Office Code Pro Premium it would seem

On Wed, Oct 7, 2015 at 11:57 PM, Ally Raza notifications@github.com wrote:

> Hi Josh,
> 
> what font are you using?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/knewter/dotfiles/issues/1.

## 

_Josh Adams_
CTO | isotope|eleven http://www.isotope11.com
[cell](205) 215-3957
[work](877) 476-8671 x201

[mail]
3800 Colonnade Pkwy
Suite 140
Birmingham, AL 35242
